import type { Brand } from './types';

export const bdi: Brand = {
  id: 'bdi',
  longName: 'La Bande des Idées',
  shortName: 'La BDI',
  description: 'Le site officiel de la Bande des Idées',
  metadataTemplate: '%s | La BDI',
  email: 'labandedesidees@gmail.com',
  facebookUrl: 'https://www.facebook.com/bandedesidees',
  instagramUrl: 'https://www.instagram.com/labandedesidees/',
  instagramHandle: '@labandedesidees',
  domain: 'bdi.fr',
  icsPRODID: '-//BDI//Bande des Idées//FR',
  icsUidSuffix: 'bdi',
  assets: {
    logo: '/brands/bdi/logo.jpg',
    hero: '/brands/bdi/hero.jpg',
    icon: '/brands/bdi/icon.png',
    appleIcon: '/brands/bdi/apple-icon.png',
    favicon: '/brands/bdi/favicon.png',
  },
  heroLayout: 'overlay',
  headingFont: 'lusitana',
  compactMobileNav: false,
  theme: {
    background: '#FAFAF8',
    foreground: '#1A1A2E',
    card: '#FFFFFF',
    cardForeground: '#1A1A2E',
    popover: '#FFFFFF',
    popoverForeground: '#1A1A2E',
    primary: '#2563EB',
    primaryForeground: '#FFFFFF',
    secondary: '#DC2626',
    secondaryForeground: '#FFFFFF',
    accent: '#F4D35E',
    accentForeground: '#1A1A2E',
    muted: '#F0EFEB',
    mutedForeground: '#6B6B6B',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    border: '#E5E4E0',
    input: '#E5E4E0',
    ring: '#2563EB',
    sidebar: '#2563EB',
    sidebarForeground: '#FFFFFF',
    sidebarAccent: '#F4D35E',
    sidebarAccentForeground: '#1A1A2E',
    sidebarBorder: '#1D4ED8',
    chart1: '#E86833',
    chart2: '#2B9A8F',
    chart3: '#3B5998',
    chart4: '#D4A843',
    chart5: '#C89B30',
    cardCycle: ['#2563EB', '#E86833', '#2B9A8F', '#F4D35E'],
    cardCycleGoldForeground: '#1A1A2E',
  },
  features: {
    crowdfunding: {
      url: 'https://fr.ulule.com/la-revue-des-idees',
      coverImage: '/brands/bdi/rdi-cover.jpg',
      title: {
        fr: 'Crowdfunding de La Revue des Idées',
        en: 'Crowdfunding for La Revue des Idées',
      },
      cta: {
        fr: 'Participer au crowdfunding',
        en: 'Support the crowdfunding',
      },
    },
  },
};
