import type { Brand } from './types';

export const cmbd: Brand = {
  id: 'cmbd',
  longName: "C'est Marseille BD",
  shortName: 'CMBD',
  description: "Le site officiel de C'est Marseille BD",
  metadataTemplate: '%s | CMBD',
  email: 'cmarseillebd@gmail.com',
  facebookUrl: 'https://www.facebook.com/profile.php?id=61572033565998',
  instagramUrl: 'https://www.instagram.com/cmarseillebd/',
  instagramHandle: '@cmarseillebd',
  domain: 'cmarseillebd.fr',
  icsPRODID: "-//CMBD//C'est Marseille BD//FR",
  icsUidSuffix: 'cmbd',
  assets: {
    // Temporary solid-colour placeholders — replace with real artwork.
    logo: '/brands/cmbd/logo.png',
    hero: '/brands/cmbd/hero.png',
    icon: '/brands/cmbd/icon.png',
    appleIcon: '/brands/cmbd/apple-icon.png',
    favicon: '/brands/cmbd/favicon.png',
  },
  theme: {
    // Marseille palette: Mediterranean blue, sun gold, terracotta, limestone white.
    background: '#FAF7F0',
    foreground: '#0B1D3A',
    card: '#FFFFFF',
    cardForeground: '#0B1D3A',
    popover: '#FFFFFF',
    popoverForeground: '#0B1D3A',
    primary: '#0077B6',
    primaryForeground: '#FFFFFF',
    secondary: '#E07A5F',
    secondaryForeground: '#FFFFFF',
    accent: '#FFC43D',
    accentForeground: '#0B1D3A',
    muted: '#EFE9DC',
    mutedForeground: '#6B6B6B',
    destructive: '#C1292E',
    destructiveForeground: '#FFFFFF',
    border: '#E4DED0',
    input: '#E4DED0',
    ring: '#0077B6',
    sidebar: '#003566',
    sidebarForeground: '#FFFFFF',
    sidebarAccent: '#FFC43D',
    sidebarAccentForeground: '#0B1D3A',
    sidebarBorder: '#00243F',
    chart1: '#0077B6',
    chart2: '#2A9D8F',
    chart3: '#E07A5F',
    chart4: '#FFC43D',
    chart5: '#023E8A',
    cardCycle: ['#0077B6', '#E07A5F', '#2A9D8F', '#FFC43D'],
    cardCycleGoldForeground: '#0B1D3A',
  },
  features: {
    // No crowdfunding for CMBD.
  },
};
