import type { Brand } from './types';

export const cmbd: Brand = {
  id: 'cmbd',
  longName: "C'est Marseille BD",
  shortName: 'CMBD',
  description: "Le site officiel de C'est Marseille BD",
  metadataTemplate: '%s | CMBD',
  email: 'cmarseillebd@gmail.com',
  facebookUrl: 'https://www.facebook.com/profile.php?id=61572033565998',
  instagramUrl: 'https://www.instagram.com/cmarseillebd/',
  instagramHandle: '@cmarseillebd',
  domain: 'cmarseillebd.fr',
  icsPRODID: "-//CMBD//C'est Marseille BD//FR",
  icsUidSuffix: 'cmbd',
  assets: {
    // Generated from the brand artwork by scripts/build-cmbd-assets.js.
    logo: '/brands/cmbd/logo.png',
    hero: '/brands/cmbd/hero.png',
    icon: '/brands/cmbd/icon.png',
    appleIcon: '/brands/cmbd/apple-icon.png',
    favicon: '/brands/cmbd/favicon.png',
  },
  heroLayout: 'logo',
  headingFont: 'darumadrop',
  compactMobileNav: true,
  theme: {
    // Palette sampled from the CMBD logo: dark blue (navy), light blue (sea),
    // yellow (sun), orange (bubble) — on the logo's cream ground.
    // NOTE: the live UI reads these values from the `.brand-cmbd` block in
    // app/ui/global.css; keep the two in sync.
    background: '#FAF7F0',
    foreground: '#0B2748',
    card: '#FFFFFF',
    cardForeground: '#0B2748',
    popover: '#FFFFFF',
    popoverForeground: '#0B2748',
    primary: '#0E80BE',
    primaryForeground: '#FFFFFF',
    secondary: '#E97F5E',
    secondaryForeground: '#FFFFFF',
    accent: '#FBC23F',
    accentForeground: '#0B2748',
    muted: '#EFE9DC',
    mutedForeground: '#6B6B6B',
    destructive: '#C1292E',
    destructiveForeground: '#FFFFFF',
    border: '#E4DED0',
    input: '#E4DED0',
    ring: '#0E80BE',
    sidebar: '#0B2748',
    sidebarForeground: '#FFFFFF',
    sidebarAccent: '#FBC23F',
    sidebarAccentForeground: '#0B2748',
    sidebarBorder: '#081B33',
    chart1: '#0E80BE',
    chart2: '#E97F5E',
    chart3: '#FBC23F',
    chart4: '#0B2748',
    chart5: '#7FB9D9',
    cardCycle: ['#0E80BE', '#E97F5E', '#0B2748', '#FBC23F'],
    cardCycleGoldForeground: '#0B2748',
  },
  features: {
    // No crowdfunding for CMBD.
  },
};
